# Generated by Django 4.2.25 on 2025-10-06 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('src_ip', models.CharField(max_length=64)),
                ('dst_ip', models.CharField(max_length=64)),
                ('proto', models.CharField(blank=True, max_length=16)),
                ('src_port', models.IntegerField(blank=True, null=True)),
                ('dst_port', models.IntegerField(blank=True, null=True)),
                ('length', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
